version: '3.9'

services:
  bytebank:
    image: bytebank:latest
    container_name: bytebank
    networks:
      - bytebank-network
    ports:
      - "3000:3000"

  bytebank-investments:
    image: bytebank-investments:latest
    container_name: bytebank-investments
    networks:
      - bytebank-network
    ports:
      - "3001:3000"

  bytebank-api:
    image: bytebank-api:latest
    container_name: bytebank-api
    networks:
      - bytebank-network
    ports:
      - "3002:3000"

networks:
  bytebank-network:
    driver: bridge
